[tool.poetry]
name = "conductor"
version = "0.1.0"
description = ""
authors = ["Leo Balduf <leobalduf@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pika = "^1.3"
requests = "^2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
